spring:
  application:
    name: cloud-eureka
  security:
    user:
      name: admin
      password: 123456

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:123456@127.0.0.1:8000/eureka/
