spring:
  application:
    name: micro-auth

server:
  port: 8001

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://admin:123456@127.0.0.1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

nacos:
  config:
    enabled: true
    bootstrap:
      enable: true
    max-retry: 5
    auto-refresh: true
    remote-first: true
    type: yaml
    data-id: micro-producer.yaml
    server-addr: 127.0.0.1:8848
    namespace: public
    group: DEFAULT_GROUP
    username: nacos
    password: nacos
  discovery:
    auto-register: true
    server-addr: 127.0.0.1:8848
    namespace: public
    username: nacos
    password: nacos
    register:
      enabled: true
      group-name: DEFAULT_GROUP
      ephemeral: true # 是否为临时实例（缺省为true）

app-info:
  apps:
    - appName: csp
      appKey: csp_app
      appSecret: 123456