spring:
  application:
    name: micro-auth

server:
  port: 8001

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://admin:123456@127.0.0.1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

app-info:
  apps:
    - appName: csp
      appKey: csp_app
      appSecret: 123456